services:
    akeneo_connectivity.connection.service.apps.client_provider:
        class: Akeneo\Connectivity\Connection\Infrastructure\Apps\OAuth\ClientProvider
        arguments:
            - '@fos_oauth_server.client_manager.default'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession:
        arguments:
            - '@session'

    Akeneo\Connectivity\Connection\Application\Apps\Command\ConfirmAppAuthorizationHandler:
        arguments:
            - '@validator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession'
            - '@akeneo_connectivity.connection.marketplace.get_app_query'
            - '@akeneo_connectivity.connection.service.user.create_user'
            - '@akeneo_connectivity.connection.service.user.create_user_group'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Service\CreateConnection'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\AppRoleWithScopesFactory'
            - '@akeneo_connectivity.connection.service.apps.client_provider'

    Akeneo\Connectivity\Connection\Application\Apps\Command\RequestAppAuthorizationHandler:
        arguments:
            - '@validator'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Session\AppAuthorizationSession'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\AppRoleWithScopesFactory:
        arguments:
            - '@pim_api.security.scope_mapper'
            - '@pim_user.factory.role'
            - '@pim_user.saver.role_with_permissions'
        public: true

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Service\CreateConnection:
        arguments:
            - '@akeneo_connectivity.connection.persistence.repository.connection'
            - '@akeneo_connectivity.connection.application.handler.find_a_connection'

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Service\AppUserProvider:
        arguments:
            - '@pim_user.manager'
            - '@pim_user.factory.user'
            - '@pim_user.updater.user'
            - '@pim_user.saver.user'
            - '@pim_user.factory.group'
            - '@pim_user.updater.group'
            - '@pim_user.saver.group'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\AppRoleWithScopesFactory'
            - '@validator'
